sudo: false
language: rust
cache: cargo

rust:
    - stable
    - beta
    - nightly

matrix:
  allow_failures:
    - rust: nightly

before_install:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      sudo apt-get -qq update
      && sudo apt-get install -y libasound2-dev libudev-dev;
    fi

script:
    cargo test --verbose --all