[package]
name = "tocenter"
version = "0.1.1"
authors = ["Dmitriy Sokolov <silentsokolov@gmail.com>"]
edition = "2018"

[dependencies]
ggez = "0.5.1"
log = "0.4.8"
env_logger = "0.6.2"
specs = "0.15.0"
specs-derive = "0.4.0"
rand = "0.6.5"

[build-dependencies]
walkdir = "2.2.9"
zip = "0.5.0"
